### PR TITLE
fix: github-pr-review path's black_check_output value

### LINKED ISSUE #56: error: When repoter "github-pr-review" error occur
https://github.com/reviewdog/action-black/blob/752e8a23953b8af9316f42ddae11417830238fbc/entrypoint.sh#L66-L68

Nomally:  reporter: "github-check" work fine
https://github.com/tsuyoshicho/pytest-sample/runs/6803763036?check_suite_focus=true

But,   reporter: "github-pr-review" error occur
https://github.com/tsuyoshicho/pytest-sample/runs/6803765264?check_suite_focus=true

```
/home/runner/work/_actions/reviewdog/action-black/v3/entrypoint.sh: line 68: unset: [-1]: bad array subscript
```

github-pr-review using command are different output?

### PR DESCRIPTION
**Pull request by tsuyoshicho**
Close #56 

In github-pr-review:
regenerate with normal command result.

### CODE REVIEW

**Comment by tsuyoshicho** [comment]
ping @haya14busa san, @rickstaa san

**Comment by rickstaa** [comment]
@tsuyoshicho Sorry for the late reply. I'm very busy with my graduation, so I didn't yet find the time to look at this PR. Maybe @haya14busa  or @chadsr have time to look at it.

File: entrypoint.sh [hunk 1]
```diff
@@ -39,6 +39,14 @@ if [[ "${INPUT_REPORTER}" = 'github-pr-review' ]]; then
     -level="${INPUT_LEVEL}" \
     -fail-on-error="${INPUT_FAIL_ON_ERROR}" \
     ${INPUT_REVIEWDOG_FLAGS} || reviewdog_exit_val="$?"
+
+  # regenerate black_check_output that command same as non-github-pr-review.
+  # because after process need normal generated black_check_output value.
+  # read and drop exit code
+  black_exit_val2="0"
+  # shellcheck disable=SC2086,SC2034
+  black_check_output="$(black --check . ${INPUT_BLACK_ARGS} 2>&1)" ||
```
Comment (rickstaa) [inline entrypoint.sh:48]: @tsuyoshicho I think this can be changed to `black_check_output="$(black --check . ${INPUT_BLACK_ARGS} 2>&1)" || true` since we don't use the exit code.

File: entrypoint.sh [hunk 2]
```diff
@@ -39,6 +39,14 @@ if [[ "${INPUT_REPORTER}" = 'github-pr-review' ]]; then
     -level="${INPUT_LEVEL}" \
     -fail-on-error="${INPUT_FAIL_ON_ERROR}" \
     ${INPUT_REVIEWDOG_FLAGS} || reviewdog_exit_val="$?"
+
+  # regenerate black_check_output that command same as non-github-pr-review.
```
Comment (rickstaa) [inline entrypoint.sh:43]: Maybe the shorter `Re-generate black output. Needed because the output of the '--diff' option can not be used to retrieve the files that black would change` is enough.

**Review by rickstaa — CHANGES_REQUESTED** [review]

**Comment by rickstaa** [comment]
@tsuyoshicho I went through your pull request. I think your pull request looks (see my suggestions above). I created a pull request on your for (see https://github.com/tsuyoshicho/action-black/pull/1). This pull request also documents the `BLACK_CHECK_FILE_PATHS` that was added by @chadsr and removes a Jupyter warning that is thrown by black when a repository contains a `.ipynb` file but Jupyter is not installed. I think with these changes we can merge #57. Let me know what you think.

**Comment by tsuyoshicho** [comment]
Thanks your fix PR. Good job!
Request re-review, @rickstaa san

**Review by rickstaa — APPROVED** [review]

**Comment by rickstaa** [comment]
LGTM thanks for the contribution!

**Comment by tsuyoshicho** [comment]
@rickstaa 
Sorry for late request.

There seems to be no update for "black" for a while, so could you please release it?

**Comment by rickstaa** [comment]
@tsuyoshicho Oh, of crouse I forgot to add the `bump:minor` label when I merged this. I just released v3.7.0 to include your feature.
